# Generated by Django 5.2 on 2025-07-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brigade_equipment_remove_chastyna_zahon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='users',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='created',
        ),
        migrations.AddField(
            model_name='equipment',
            name='brigade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.brigade'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='acts/'),
        ),
        migrations.AddField(
            model_name='testing',
            name='next_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='detachments',
            field=models.ManyToManyField(blank=True, to='core.detachment'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testing',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testings', to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('GOD', 'God'), ('RO', 'Read Only'), ('RW', 'Read Write')], default='RO', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='testing',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='tested_at',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='tested_by',
        ),
    ]
